### PR TITLE
chore: move from travis to github actions

### PR DESCRIPTION
**Pull request by winged**

### CODE REVIEW

**Comment by winged** [comment]
Note: Disabled travis check requirement for now. Will add github check requirement after this is merged

**Comment by winged** [comment]
Also note - the fix to the current failure is already in #370, so will rebase once that one's merged

**Review by sbor23 — APPROVED** [review]

**Comment by sbor23** [comment]
Nice! Just for understanding, do the linting step and the pytest step happend sequencially? Does linting block testing if it fails?

**Comment by winged** [comment]
> Nice! Just for understanding, do the linting step and the pytest step happend sequencially? Does linting block testing if it fails?

I just stole this from Caluma. The "gitlint" and "test" steps happen in parallel, but we didn't parallelize the linters within the test

**Pull request merged**
