### PR TITLE
feat: increase slug field max length to 1048

### PR DESCRIPTION
**Pull request by Yelinz**

### CODE REVIEW

**Comment by winged** [comment]
Not sure this is a good idea. Why do we need this?

**Comment by Yelinz** [comment]
The default max_length of 50 on a SlugField is quite limited and doesn't allow for longer slugs, if for example the file name plus some other information were used to generate the slug. It would exceed 50 characters quickly.

**Comment by winged** [comment]
> The default max_length of 50 on a SlugField is quite limited and doesn't allow for longer slugs, if for example the file name plus some other information were used to generate the slug. It would exceed 50 characters quickly.

Slugs are meant to be short, (human) readable identifiers. While I agree that 50 chars is too short, 1k (1042chars, how did you get to this number, btw?) is way too long. That's about 13 lines of text. I suggest changing your client code to shorten the slugs instead of using full file names and more to make one.

See also the discussion in https://github.com/projectcaluma/caluma/pull/962 where we decided that slugs in Caluma should be 127chars.

I'm willing to accept 250chars for slugs, but if your code tends to exceed that limit, there's most likely something sub-ideal going on

**Comment by anehx** [comment]
This is certainly not the idea.. @Yelinz let's discuss this tomorrow, I think you misinterpreted the task at hand

**Pull request closed without merging**
